---
deployment:
  tasks:
    - export DEPLOYPATH=/project/back
    - /gotagota.sintraunipricol.com.co -R $DEPLOYPATH
---
deployment:
  tasks:
    - export DEPLOYPATH=/gotagota.sintraunipricol.com.co 
    - /project/back -R . $DEPLOYPATH
