name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: mostrar directorios y archivos
      run: ls
    - name: abrir carpeta project
      working-directory: ./project/back
      run: composer install --prefer-dist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-dev
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files to sintra
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.sintraunipricol.com.co
        username: gotagota@gotagota.sintraunipricol.com.co
        password: ${{ secrets.ftp_password }}
